title: "taking time.to"
remote_theme: riggraz/no-style-please
url: https://takingtime.to

permalink: /:slug.html

theme_config:
  appearance: "light"
  back_home_text: "go back"
  show_description: false
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed