title: "taking time.to"
remote_theme: riggraz/no-style-please
url: https://takingtime.to
theme_config:
  appearance: "light"
  back_home_text: "go back"
  show_description: false

plugins:
  - jekyll-feed